spring:
  datasource:
    url: @jdbc_mysql_url@
    username: @jdbc_username@
    password: @jdbc_pwd@
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 自动建表
  #    schema: classpath:schema-mysql.sql
  #    initialization-mode: always
  profiles:
    active: @profiles.active@
  redis:
    database: 0
    host: @host@
    #    host: 127.0.0.1
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.light.timetable.entity
    #  configuration:
  #日志打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 80


jwt:
  key: lighttimetable
image:
  save-path: /images
